# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=com.lumii.armory

# Dependencies
fabric_api_version=0.92.11+1.20.1
reflect_ver = 1.20.1-1.0.0
ozone_version = 1.0.0+1.20.1
midnightlib_version=1.4.1-fabric
lodestone_version=1.6.2.3f
trinkets_version=3.7.2
cca_version=5.2.3
port_lib_version = 2.3.4+1.20.1
port_lib_modules = \
  accessors,\
  base,\
  blocks,\
  core,\
  data,\
  extensions,\
  lazy_registration,\
  model_generators,\
  models,\
  networking,\
  tool_actions
rea_version= 2.4.0
